training_data = [
        ("I want to order my medication", "order"),
        ("I want to place an order for my medication.", "order"),
        ("Can you help me order my medication?", "order"),
        ("How can I order my medication?", "order"),
        ("I need to order my prescribed medication.", "order"),
        ("Please assist me with ordering my medication.", "order"),
        ("I'm interested in ordering my medication.", "order"),


        ("I want to know the status of my order.", "status"),
        ("Can you help me check the status of my order?", "status"),
        ("How can I check the status of my order?", "status"),
        ("I need to know the status of my placed order.", "status"),
        ("Please assist me with checking my order status.", "status"),


        ("What is Aspirin used for?", "medication_info"),
        ("Can you tell me about Vitamin D?", "medication_info"),
        ("How should I take Tylenol?", "medication_info"),
        ("What's the recommended dosage for Omega-3?", "medication_info"),
        ("Should I take Probiotics with food?", "medication_info"),
        ("How often should I use Iron supplements?", "medication_info"),
        ("Can I take Ibuprofen with Antibiotics?", "medication_info"),
        ("Are there any interactions between Lisinopril and Metformin?", "medication_info"),
        ("Is it safe to use Penicillin if I'm allergic to Penicillin?", "medication_info"),
        ("Does Amoxicillin contain gluten?", "medication_info"),
        ("What are the common side effects of Prednisone?", "medication_info"),
        ("Can Statins cause muscle pain?", "medication_info"),
        ("Are there any alternatives to Xanax?", "medication_info"),
        ("How should I store Levothyroxine?", "medication_info"),
        ("Do I need a prescription for Atorvastatin?", "medication_info"),
        ("How long should I continue using Birth Control pills?", "medication_info"),
        ("What should I do if I miss a dose of Antidepressants?", "medication_info"),
        ("Is it safe to use Ibuprofen during pregnancy or while breastfeeding?", "medication_info"),
        ("Tell me about Prozac.", "medication_info"),
        ("How can I get more information about medications?", "medication_info"),
        ("I'm not sure what to ask, but I have a question about supplements.", "medication_info"),
        ("That's all I need for now. Thank you.", "medication_info"),
        ("Hello! Can you help me with some questions about medications?", "medication_info"),



        ("I've got everything I was looking for. That's it for now.", "exit"),
        ("You've been great. I don't require any more help.", "exit"),
        ("I'm all set. Thanks for your time and assistance.", "exit"),
        ("I'm ready to wrap things up. I don't need any additional help.", "exit"),
        ("That's all, thanks", "exit"),
        ("I'm fine thanks", "exit"),
        ("Exit", "exit"),
        ("Cancel", "exit"),
        ("Quit", "exit"),
        ("No thank you", "exit"),
        ("Nothing else", "exit"),
    ]